services:
  app:
    build: ./app
    container_name: app
    restart: always

  web:
    image: cr.yandex/mirror/nginx:latest
    container_name: web
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app